theme: minima
title: Will's Blog
author: Will McGill
email: mcgill.will@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I'm going to put all the awesome new things that I am learning.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
